import Head from "next/head";
import Image from "next/image";

import Button from "@mui/material/Button";
import TextField from "@mui/material/TextField";

import styles from "../../styles/Home.module.css";

import Layout from "../../components/layout";

import TopBar from "../../components/topbar/topBar";
import MenuBar from "../../components/menuBar/menubar";

import profileStyle from "../../styles/profile.module.css";

import React, { useState } from "react";
import { Controller, useForm } from "react-hook-form";

export default function ProfilePage() {
  const { register, handleSubmit, reset, control } = useForm();
  const onSubmit = (data) => console.log(data);

  return (
    <Layout>
      <>
        <Head>
          <title> Account Profile </title>{" "}
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>{" "}
        <TopBar> </TopBar>
        <div className={profileStyle.container}>
          <h1 className={profileStyle.accountProfile}> Account Profile </h1>
          <div className={profileStyle.imageWrapper}>
            <Image
              src="/images/teacher.jpg" // Route of the image file
              height={200} // Desired size with correct aspect ratio
              width={200} // Desired size with correct aspect ratio
              alt="Avatar"
              className={profileStyle.image}
            />
          </div>
          <form>
            <Controller
              name={"textValue"}
              control={control}
              render={({ field: { onChange, value } }) => (
                <>
                  <div className={profileStyle.textFieldWrapper}>
                    <TextField
                      required
                      id="outlined-required"
                      label="Your name:"
                      defaultValue=""
                      onChange={onChange}
                      className={profileStyle.textField}
                      {...register("txtName")}
                    />
                    <br></br>
                  </div>
                  <div className={profileStyle.textFieldWrapper}>
                    {" "}
                    <TextField
                      required
                      id="outlined-required"
                      label="Code: "
                      defaultValue=""
                      onChange={onChange}
                      className={profileStyle.textField}
                      {...register("txtCode")}
                    />
                    <br></br>
                  </div>

                  <div className={profileStyle.textFieldWrapper}>
                    {" "}
                    <TextField
                      required
                      id="outlined-required"
                      label="Discription:"
                      defaultValue=""
                      disabled
                      onChange={onChange}
                      className={profileStyle.textField}
                    />
                    <br></br>
                  </div>

                  <div className={profileStyle.textFieldWrapper}>
                    <TextField
                      required
                      id="outlined-required"
                      disabled
                      label="Room:"
                      defaultValue=""
                      onChange={onChange}
                      className={profileStyle.textField}
                    />
                    <br></br>
                  </div>
                </>
              )}
            />
            <div className={profileStyle.buttonWrapper}>
              <Button
                onClick={handleSubmit(onSubmit)}
                variant={"outlined"}
                className={profileStyle.button}
              >
                Reset
              </Button>
              <Button
                onClick={handleSubmit(onSubmit)}
                className={profileStyle.button}
                variant="contained"
              >
                Submit
              </Button>
            </div>
          </form>
        </div>{" "}
      </>{" "}
    </Layout>
  );
}
