import Head from "next/head";
import Image from "next/image";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";

import styles from "../../../styles/util.module.css";

import Layout from "../../../components/layout";

import TopBarClassDetail from "../../../components/topBarClassDetail/topBarClassDetail";
import MenuBar from "../../../components/menuBar/menubar";
import ClassRoom from "../../../components/classroom/classroom";
import Lesson from "../../../components/classroom/detail/lesson";
import Banner from "../../../components/classroom/detail/bannerClassDetail";
import Upcoming from "../../../components/classroom/detail/upComingHomeWork";

import libClassroom from "../../../lib/classroom";

export async function getStaticProps({ params }) {
  const classDetail = libClassroom[parseInt(params.id)];
  return {
    props: {
      classDetail,
    },
  };
}

export async function getStaticPaths() {
  const paths = [
    { params: { id: "1" } },
    { params: { id: "2" } },
    { params: { id: "31" } },
    { params: { id: "4" } },
  ];
  return {
    paths,
    fallback: false,
  };
}

export default function ClassroomDetailPage({ classDetail }) {
  const listLesson = [
    { personPost: classDetail.host },
    { personPost: classDetail.host },
    { personPost: classDetail.host },
    { personPost: classDetail.host },
  ];
  return (
    <Layout>
      <>
        <Head>
          <title>Detail Class</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <TopBarClassDetail></TopBarClassDetail>
        <div className={styles.classContentDetailContainer}>
          <Banner classroomName={classDetail.className}></Banner>
          <Grid container spacing={2}>
            <Grid item xs={3}>
              <Upcoming></Upcoming>
            </Grid>{" "}
            <Grid item xs={9}>
              <Stack spacing={2}>
                {listLesson.map((lesson) => {
                  return <Lesson lesson={lesson}></Lesson>;
                })}
              </Stack>
            </Grid>{" "}
          </Grid>{" "}
        </div>
      </>
    </Layout>
  );
}
