import Head from "next/head";
import Image from "next/image";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";

import styles from "../../styles/Home.module.css";

import Layout from "../../components/layout";

import TopBarClassDetail from "../../components/topBarClassDetail/topBarClassDetail";
import MenuBar from "../../components/menuBar/menubar";
import ClassRoom from "../../components/classroom/classroom";
import Lesson from "../../components/classroom/detail/lesson";
import Banner from "../../components/classroom/detail/bannerClassDetail";

export default function ClassRoomPage() {
  return (
    <Layout>
      <>
        <div className={styles.container}>
          <Head>
            <title>Detail Class</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <TopBarClassDetail></TopBarClassDetail>
          <Banner></Banner>
          <Grid container spacing={2}>
            <Grid item xs={2}>
              hello
            </Grid>{" "}
            <Grid item xs={10}>
              <Stack spacing={2}>
                <Lesson></Lesson>
                <Lesson></Lesson>
                <Lesson></Lesson>
                <Lesson></Lesson>
              </Stack>
            </Grid>{" "}
          </Grid>{" "}
        </div>
      </>
    </Layout>
  );
}
