import Head from "next/head";
import Image from "next/image";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import Divider from "@mui/material/Divider";

import Layout from "../../components/layout";

import TopBarClassDetail from "../../components/topBarClassDetail/topBarClassDetail";
import MenuBar from "../../components/menuBar/menubar";
import ClassRoom from "../../components/classroom/classroom";
import Lesson from "../../components/classroom/detail/lesson";
import Banner from "../../components/classroom/detail/bannerClassDetail";

import Person from "../../components/classroom/people/person";
import styles from "../../styles/util.module.css";

import peopleStyle from "../../styles/classroom.people.module.css";

import libClassroom from "../../lib/classroom";

export async function getStaticProps() {
  const teacherList = [
    { personName: "Dương Bội Long" },
    { personName: "Võ Thế Minh" },
    { personName: "Phạm Tống Bình Minh" },
  ];
  const studentList = [
    { personName: "Phạm Tống Bình Minh" },
    { personName: "Võ Thế Minh" },

    { personName: "Dương Bội Long" },

    { personName: "Dương Bội Long" },

    { personName: "Dương Bội Long" },

    { personName: "Dương Bội Long" },
  ];
  return {
    props: {
      teacherList,
      studentList,
    },
  };
}

export default function ClassRoomPage({ teacherList, studentList }) {
  return (
    <Layout>
      <>
        <Head>
          <title>People in class</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <TopBarClassDetail></TopBarClassDetail>
        <div className={styles.classContentPeopleContainer}>
          <Grid container spacing={2}>
            <Grid item xs={10}>
              <h1 style={{ color: "#1967D3" }}>Teachers</h1>
            </Grid>
            <Grid item xs={2}>
              <p className={peopleStyle.number}>
                {teacherList.length} teachers
              </p>
            </Grid>
          </Grid>
          <List>
            {teacherList.map((teacher) => {
              return (
                <>
                  <ListItem>
                    <Person personName={teacher.personName}></Person>
                  </ListItem>
                  <Divider />
                </>
              );
            })}
          </List>
          <Grid container spacing={2}>
            <Grid item xs={10}>
              <h1 style={{ color: "#1967D3" }}>Students</h1>
            </Grid>
            <Grid item xs={2}>
              <p className={peopleStyle.number}>
                {studentList.length} students
              </p>
            </Grid>
          </Grid>
          <List>
            {studentList.map((student) => {
              return (
                <>
                  <ListItem>
                    <Person personName={student.personName}></Person>
                  </ListItem>
                  <Divider />
                </>
              );
            })}
          </List>
        </div>
      </>
    </Layout>
  );
}
