import Head from "next/head";
import Image from "next/image";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import Divider from "@mui/material/Divider";

import Layout from "../../components/layout";

import TopBarClassDetail from "../../components/topBarClassDetail/topBarClassDetail";
import MenuBar from "../../components/menuBar/menubar";
import ClassRoom from "../../components/classroom/classroom";
import Lesson from "../../components/classroom/detail/lesson";
import Banner from "../../components/classroom/detail/bannerClassDetail";

import Person from "../../components/classroom/people/person";
import styles from "../../styles/util.module.css";

import peopleStyle from "../../styles/classroom.people.module.css";

export default function ClassRoomPage() {
  return (
    <Layout>
      <>
        <Head>
          <title>People in class</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <TopBarClassDetail></TopBarClassDetail>
        <div className={styles.classContentPeopleContainer}>
          <Grid container spacing={2}>
            <Grid item xs={10}>
              <h1 style={{ color: "#1967D3" }}>Teacher</h1>
            </Grid>
            <Grid item xs={2}>
              <p className={peopleStyle.number}>Number</p>
            </Grid>
          </Grid>
          <List>
            <ListItem>
              <Person></Person>
            </ListItem>
            <Divider />
            <ListItem>
              <Person></Person>
            </ListItem>
            <Divider />
            <ListItem>
              <Person></Person>
            </ListItem>
            <Divider />
          </List>
          <Grid container spacing={2}>
            <Grid item xs={10}>
              <h1 style={{ color: "#1967D3" }}>Classmates</h1>
            </Grid>
            <Grid item xs={2}>
              <p className={peopleStyle.number}>Number</p>
            </Grid>
          </Grid>
          <List>
            <ListItem>
              <Person></Person>
            </ListItem>
            <Divider />
            <ListItem>
              <Person></Person>
            </ListItem>

            <Divider />
            <ListItem>
              <Person></Person>
            </ListItem>
            <Divider />
          </List>
        </div>
      </>
    </Layout>
  );
}
