import Head from "next/head";
import Image from "next/image";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import Divider from "@mui/material/Divider";

import Layout from "../../components/layout";

import TopBarClassDetail from "../../components/topBarClassDetail/topBarClassDetail";
import MenuBar from "../../components/menuBar/menubar";
import ClassRoom from "../../components/classroom/classroom";
import Lesson from "../../components/classroom/detail/lesson";
import Banner from "../../components/classroom/detail/bannerClassDetail";

import Person from "../../components/classroom/people/person";
import styles from "../../styles/util.module.css";

import peopleStyle from "../../styles/classroom.people.module.css";

import libClassroom from "../../lib/classroom";

import { useState, useEffect } from "react";
import Cookie from "js-cookie";

export default function ClassRoomPage() {
  const [studentList, setStudentList] = useState([]);
  const [teacherList, setTeacherList] = useState([]);
  const [loadingPage, setLoadingPage] = useState(true);

  useEffect(() => {
    const classDetail = JSON.parse(Cookie.get("classDetail"));
    const studentListTemp = [];
    const teacherListTemp = [];
    classDetail.members.map((member) => {
      if (member.userType === "Teacher") {
        teacherListTemp.push(member);
      } else {
        studentListTemp.push(member);
      }
    });

    setTeacherList(teacherListTemp);
    setStudentList(studentListTemp);
    setLoadingPage(false);
  });
  return (
    <div>
      {!loadingPage ? (
        <Layout>
          <>
            <Head>
              <title>People in class</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopBarClassDetail></TopBarClassDetail>
            <div className={styles.classContentPeopleContainer}>
              <Grid container spacing={2}>
                <Grid item xs={10}>
                  <h1 style={{ color: "#1967D3" }}>Teachers</h1>
                </Grid>
                <Grid item xs={2}>
                  <p className={peopleStyle.number}>
                    {teacherList.length} teachers
                  </p>
                </Grid>
              </Grid>
              <List>
                {teacherList.map((teacher) => {
                  return (
                    <>
                      <ListItem>
                        <Person personName={teacher.email}></Person>
                      </ListItem>
                      <Divider />
                    </>
                  );
                })}
              </List>
              <Grid container spacing={2}>
                <Grid item xs={10}>
                  <h1 style={{ color: "#1967D3" }}>Students</h1>
                </Grid>
                <Grid item xs={2}>
                  <p className={peopleStyle.email}>
                    {studentList.length} students
                  </p>
                </Grid>
              </Grid>
              <List>
                {studentList.map((student) => {
                  return (
                    <>
                      <ListItem>
                        <Person personName={student.personName}></Person>
                      </ListItem>
                      <Divider />
                    </>
                  );
                })}
              </List>
            </div>
          </>
        </Layout>
      ) : (
        <></>
      )}
    </div>
  );
}
